---
- name: Create WireGuard client config
  hosts: mon
  become: true
  vars_files:
    - group_vars/all/wireguard.yml

  pre_tasks:
    - name: Debug wg_client_ip
      debug:
        var: wg_client_ip

  tasks:
    - name: Read server public key
      shell: cat /etc/wireguard/server.key | wg pubkey
      register: server_pub_key
      no_log: true

    - name: Read client private key
      shell: cat /etc/wireguard/client.key
      register: client_priv_key
      no_log: true

    - name: Create client config
      copy:
        dest: /tmp/client.conf
        content: |
          [Interface]
          PrivateKey = {{ client_priv_key.stdout }}
          Address = {{ wg_client_ip }}
          DNS = 8.8.8.8

          [Peer]
          PublicKey = {{ server_pub_key.stdout }}
          Endpoint = {{ mon_server_public_ip }}:{{ wg_listen_port }}
          AllowedIPs = {{ wg_network }}, {{ app_server_monitor_ip }}/32, {{ mon_server_monitor_ip }}/32
          PersistentKeepalive = 25
        mode: '0600'

    - name: Display client config location
      debug:
        msg: "Client config created at /tmp/client.conf on {{ inventory_hostname }}"

